-- SafeNight Snowflake Database Schema
-- Run these commands in the Snowflake console to set up the database

-- Create database and schema
CREATE DATABASE IF NOT EXISTS SAFENIGHT_DB;
USE DATABASE SAFENIGHT_DB;
CREATE SCHEMA IF NOT EXISTS APP_DATA;
USE SCHEMA APP_DATA;

-- Users table
CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR(36) PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(100) NOT NULL,
    WEIGHT NUMBER,
    GENDER VARCHAR(10),
    SOS_CODE_WORD VARCHAR(50),
    SETTINGS VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Emergency Contacts
CREATE TABLE IF NOT EXISTS EMERGENCY_CONTACTS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) REFERENCES USERS(ID),
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    RELATIONSHIP VARCHAR(50)
);

-- Drinks (for drink history)
CREATE TABLE IF NOT EXISTS DRINKS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) REFERENCES USERS(ID),
    NAME VARCHAR(100),
    ALCOHOL_TYPE VARCHAR(20),
    ESTIMATED_OZ NUMBER(5,2),
    ESTIMATED_ABV NUMBER(4,3),
    LOGGED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Venues (for geo-queries)
CREATE TABLE IF NOT EXISTS VENUES (
    ID VARCHAR(36) PRIMARY KEY,
    NAME VARCHAR(200),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    TYPE VARCHAR(50),
    SAFETY_RATING NUMBER(2,1)
);

-- Night Plans
CREATE TABLE IF NOT EXISTS NIGHT_PLANS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) REFERENCES USERS(ID),
    TITLE VARCHAR(200),
    DEPARTURE_TIME TIMESTAMP_NTZ,
    RETURN_TIME TIMESTAMP_NTZ,
    TRANSPORTATION VARCHAR(50),
    STATUS VARCHAR(20) DEFAULT 'draft',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- SOS Events
CREATE TABLE IF NOT EXISTS SOS_EVENTS (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) REFERENCES USERS(ID),
    TRIGGER_TYPE VARCHAR(20),
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    ADDRESS VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'active',
    BLOCKCHAIN_HASH VARCHAR(128),
    BLOCKCHAIN_SIGNATURE VARCHAR(256),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT TIMESTAMP_NTZ
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_EMERGENCY_CONTACTS_USER ON EMERGENCY_CONTACTS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_DRINKS_USER ON DRINKS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_DRINKS_LOGGED_AT ON DRINKS(LOGGED_AT);
CREATE INDEX IF NOT EXISTS IDX_VENUES_LOCATION ON VENUES(LATITUDE, LONGITUDE);
CREATE INDEX IF NOT EXISTS IDX_NIGHT_PLANS_USER ON NIGHT_PLANS(USER_ID);
CREATE INDEX IF NOT EXISTS IDX_SOS_EVENTS_USER ON SOS_EVENTS(USER_ID);
